[project]
name = "mypackage"
version = "0.0.1"
dependencies = [
    "calendar",
    "sqlite3",
    "smtplib",
    "os",
    "threading",
    "time",
    "werkzeug.security",
    "uuid",
    "yaml",
    "flask",
    "flask_login",
]